### ISSUE TITLE
Can't use with angular after latest typings change

### ISSUE THREAD

**Issue by sublime392** [stipsan/scroll-into-view-if-needed#135]
I now get `node_modules/scroll-into-view-if-needed/typings has no default export.` I'm not sure if there is something I can do differently on my end. Any thoughts?

**Comment by stipsan** [comment]
Hey @sublime392 thanks for reporting!

Have you tried changing the import?
```diff
-import scrollIntoViewIfNeeded from 'scroll-into-view-if-needed'
+import * as scrollIntoViewIfNeeded from 'scroll-into-view-if-needed'
```

If it still fails I'll look at it later today. The plan is to rewrite this project to use typescript directly instead of just a separate typings file that easily get outdated 😄

**Comment by sublime392** [comment]
Thanks. I did try importing it that way but I got a different error.
`node_modules/scroll-into-view-if-needed/typings"' resolves to a non-module entity and cannot be imported using this construct.`

**Comment by stipsan** [comment]
ok thanks, I've just started working on a fix 😄

**Comment by stipsan** [comment]
I've finished moving to TS and it should be working properly now :)

**Comment by stipsan** [comment]
Hi again, I just published  [1.2.8](https://github.com/stipsan/scroll-into-view-if-needed/releases/tag/v1.2.8) after discovering that the typings file was missing.
It should be included now and provide you with accurate definitions.

Since the project is now itself using TS it means the definitions include a few new features (still) not documented in the readme. `finalElement` and `OffsetConfig`.
`finalElement` is a feature that limits the boundary scrollIntoViewIfNeeded uses to calculate where it should scroll to. This is useful if you have multiple scrollbars and don't want to scroll parent scrollbars.

The `OffsetConfig` is for giving the element a margin when you scroll without resorting to CSS.
These features will be changed in `v2.0.0` of this project as I want to improve the API interface so you don't have 5 arguments which is confusing to most people wanting to use this package 😄

**Comment by sublime392** [comment]
Thanks for the fast update. I'll cycle back around in a few days to try it out.

**Comment by stipsan** [comment]
I’ll close it meanwvile. Reopen it please if it’s still happening 😄
