### ISSUE TITLE
console.log('test) left in code

### ISSUE THREAD

**Issue by Ddk34** [stipsan/scroll-into-view-if-needed#250]
Hi, theres a console.log('test) in the alignNearestInline function.

**Comment by stipsan** [comment]
Yikes! Thanks for reporting! I'm gonna add an linter rule to prevent it from sneaking in again 😄

**Comment by stipsan** [comment]
wait, I can't find it. What version is this?

**Comment by stipsan** [comment]
This error were in a pre-release of v2: https://github.com/stipsan/scroll-into-view-if-needed/blob/ec038fe211a25aaee0e9433bbd12b1ed94cc02ed/packages/scroll-into-view-if-needed/src/compute.ts#L149-L162

The functions `alignNearestInline` and `alignNearestBlock` was combined into a shared `alignNearest` function in the `2.1.1` prerelease https://github.com/stipsan/scroll-into-view-if-needed/commit/5068ad922b173a1ea3f9705ae10faa474f22a633#diff-9a0f3e8246354a0d47a96969f9b23aaa

The weird prerelease naming scheme was because of a limitation in the semantic release setup. The first stable v2 release is https://github.com/stipsan/scroll-into-view-if-needed/releases/tag/v2.1.3

I recommend you use the latest stable release as it not only don't have a `console.log('test')` calls, but don't suffer from problems with border widths or problems with `block: 'nearest'`.

I've added some protection on the CI though so it's not possible to leave console calls in the codebase by accident anymore: https://github.com/stipsan/scroll-into-view-if-needed/pull/252
